apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
  namespace: etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:v3.4.13
        ports:
        - containerPort: 2379
        - containerPort: 2380
        volumeMounts:
        - name: etcd-data
          mountPath: /etcd-data
        - name: etcd-config
          mountPath: /etc/etcd
          subPath: etcd.conf.yaml
      volumes:
      - name: etcd-data
        persistentVolumeClaim:
          claimName: etcd-pvc
      - name: etcd-config
        configMap:
          name: etcd-config
