# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apisix-java-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apisix-java
  template:
    metadata:
      labels:
        app: apisix-java
    spec:
      containers:
      - name: apisix-java-container
        image: rizqia/apisix-java-jdk17:demo-3
        ports:
        - containerPort: 8080
